In [2]:
import pandas as pd
from transformers import AutoTokenizer
import os
from datasets import load_from_disk

/Users/abdulvajid/AI/PROJECTS/Image-Caption-Generation-VIT-From-Scratch/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/abdulvajid/AI/PROJECTS/Image-Caption-Generation-VIT-From-Scratch/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:


tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "A dog is playing with a ball"
tokens = tokenizer(text)

print(tokens["input_ids"])

[101, 1037, 3899, 2003, 2652, 2007, 1037, 3608, 102]


In [5]:
import torch
torch.cuda.is_available()

True

In [8]:
len(tokenizer)

30522

In [3]:
from vit import VIT

/opt/conda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[101, 1037, 3899, 2003, 2652, 2007, 1037, 3608, 102]


In [1]:
from model_args import Arguments
args = Arguments()

In [6]:
sum(torch.numel(param) for param in VIT(args).parameters())

132603450

In [13]:
for param in VIT(args).parameters():
    print(param)

Parameter containing:
tensor([[ 0.8713,  0.5688, -1.3534,  ..., -0.9856, -1.3802, -1.5071],
        [-0.2903,  0.7216, -0.8289,  ..., -0.0403,  0.5643,  0.2452],
        [ 0.5765, -1.8812,  2.2394,  ..., -0.3839,  0.6726,  0.3462],
        ...,
        [ 0.0062, -0.9363,  0.4930,  ..., -1.0254,  0.4098, -1.7568],
        [-1.1440, -0.5073, -1.2521,  ...,  1.1072, -0.0662, -0.0601],
        [ 1.1212, -1.5451, -1.6520,  ...,  0.4010, -2.2789,  0.5962]],
       requires_grad=True)
Parameter containing:
tensor([[[[ 2.5830e-02, -7.6887e-03, -3.1998e-02,  ..., -9.9927e-03,
            8.8449e-04, -2.8876e-02],
          [-2.2287e-02,  2.0069e-02, -3.5260e-02,  ...,  1.0923e-02,
           -1.4844e-02, -2.5667e-02],
          [-2.9170e-02,  1.4827e-03,  1.4746e-02,  ...,  1.5854e-02,
            2.6354e-02,  3.3654e-02],
          ...,
          [-9.4103e-03, -1.7104e-02, -2.5365e-02,  ..., -3.6252e-03,
           -1.7382e-02, -5.2886e-04],
          [-1.2167e-02,  3.1775e-02,  3.1369e-02,  .

In [ ]:
import os

TypeError: getatime() missing 1 required positional argument: 'filename'

In [45]:
with open('archive/annotations_trainval2014/annotations/captions_train2014.json', 'r') as f:
    data = json.load(f)

In [46]:
import pandas as pd

In [47]:
images_data = pd.DataFrame(data['images'])
annotation_data = pd.DataFrame(data['annotations'])

In [48]:
data = annotation_data.merge(images_data, how='left', left_on='image_id', right_on='id')

In [49]:
data = data.drop(columns=['id_x', 'license', 'height', 'width', 'date_captured', 'flickr_url','coco_url', 'id_y', 'image_id'])

In [50]:
data = pd.read_csv('processed_caption.csv')

In [51]:
data

caption  \
0          A very clean and well decorated empty bathroom   
1       A panoramic view of a kitchen and all of its a...   
2       A blue and white bathroom with butterfly theme...   
3          A panoramic photo of a kitchen and dining room   
4       A graffiti-ed stop sign across the street from...   
...                                                   ...   
414108  a slice of bread is covered with a sour cream ...   
414109  A long plate hold some fries with some sliders...   
414110       Two women sit and pose with stuffed animals.   
414111  White Plate with a lot of guacamole and an ext...   
414112      A dinner plate has a lemon wedge garnishment.   

                                                file_name  
0       archive/train2014/train2014/COCO_train2014_000...  
1       archive/train2014/train2014/COCO_train2014_000...  
2       archive/train2014/train2014/COCO_train2014_000...  
3       archive/train2014/train2014/COCO_train2014_000...  
4       archive/train2014/train2014/COCO_train2014_000...  
...                                                   ...  
414108  archive/train2014/train2014/COCO_train2014_000...  
414109  archive/train2014/train2014/COCO_train2014_000...  
414110  archive/train2014/train2014/COCO_train2014_000...  
414111  archive/train2014/train2014/COCO_train2014_000...  
414112  archive/train2014/train2014/COCO_train2014_000...  

[414113 rows x 2 columns]

In [52]:
# convert to huggingface dataset for easy manipulation

In [53]:

load_from_disk('caption_dataset')

FileNotFoundError: No such files: '/Users/abdulvajid/AI/PROJECTS/Image-Caption-Generation-VIT-From-Scratch/caption_dataset/train/dataset_info.json', nor '/Users/abdulvajid/AI/PROJECTS/Image-Caption-Generation-VIT-From-Scratch/caption_dataset/train/state.json' found. Expected to load a `Dataset` object but provided path is not a `Dataset`.

In [72]:
data['file_name'] = data['file_name'].apply(lambda x: os.path.join('archive/train2014/train2014', x))

In [73]:
data.to_csv('processed_caption.csv', index=False)

In [2]:
import datasets

/Users/abdulvajid/AI/PROJECTS/Image-Caption-Generation-VIT-From-Scratch/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/abdulvajid/AI/PROJECTS/Image-Caption-Generation-VIT-From-Scratch/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [55]:
import datasets

In [56]:
data = datasets.load_dataset('csv', data_files='processed_caption.csv')
# data = datasets.load_dataset('caption_dataset')

In [57]:
data['train'][0]

{'caption': 'A very clean and well decorated empty bathroom',
 'file_name': 'archive/train2014/train2014/COCO_train2014_000000318556.jpg'}

In [58]:
data

DatasetDict({
    train: Dataset({
        features: ['caption', 'file_name'],
        num_rows: 414113
    })
})

In [75]:
def tokenize(sample):
    tokens = tokenizer(sample['caption']+ "[SEP]", padding='max_length', truncation=True, max_length=32, add_special_tokens=False)
    return {'input_ids': tokens['input_ids'], "attention_mask": tokens['attention_mask']}

In [76]:
data = data.map(tokenize, batched=False, num_proc=3)

Map (num_proc=3): 100%|██████████| 414113/414113 [00:08<00:00, 46022.08 examples/s]


In [74]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [78]:
tokenizer.decode(data['train'][1]['input_ids'])

'a panoramic view of a kitchen and all of its appliances. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [ ]:
)

tensor([ 1037,  6090,  6525,  7712,  3193,  1997,  1037,  3829,  1998,  2035,
         1997,  2049, 22449,  1012,   102,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0])

In [101]:
len(data['train'][0]['input_ids'])

32

In [80]:
data.save_to_disk('caption_data')

Saving the dataset (1/1 shards): 100%|██████████| 414113/414113 [00:00<00:00, 2378362.58 examples/s]


In [81]:
data = load_from_disk('caption_data')

In [ ]:
data[

KeyError: "Invalid key: 0. Please first select a split. For example: `my_dataset_dictionary['train'][0]`. Available splits: ['train']"

In [105]:
data.save_to_disk('caption_data')

Saving the dataset (1/1 shards): 100%|██████████| 414113/414113 [00:00<00:00, 3791126.14 examples/s]


In [91]:
data = load_from_disk('caption_dataset')

In [106]:
from torch.utils.data import DataLoader, Dataset
import pandas as pd
from model_args import Arguments
from torchvision import transforms
from PIL import Image
import torch
from datasets import load_dataset

args = Arguments()


class ImageCaptionData(Dataset):
    def __init__(self, path='caption_data'):
        super().__init__()
        self.path = path
        self.data = load_from_disk(path)['train']
        self.data.set_format('torch')
        
    
    def __len__(self):
        return self.data.shape[0]
    
    def __getitem__(self, index):
        print(self.data[index])
        return transform(self.data[index]['file_name']), self.data[index]['input_ids']
        

def get_dataloader():
    dataloader = DataLoader(dataset=ImageCaptionData(), batch_size=args.batch_size, num_workers=args.num_workers, shuffle=True, pin_memory=args.pin_memory)
    return dataloader


def transform(img_path):
    transformer = transforms.Compose([
        transforms.ToTensor(),
        transforms.Resize((args.img_size, args.img_size)),
        transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
    ])
    
    
    img = Image.open(img_path)
    transformed_img = transformer(img)
    
    return transformed_img

In [107]:
dataloader = get_dataloader()

In [108]:
for img, label in dataloader:
    print(img.shape)
    print(len(label))
    break

{'caption': 'A man wearing a safety vest performs a maintenance task on a fire hydrant.', 'file_name': 'archive/train2014/train2014/COCO_train2014_000000077533.jpg', 'input_ids': tensor([ 1037,  2158,  4147,  1037,  3808, 17447, 10438,  1037,  6032,  4708,
         2006,  1037,  2543, 26018,  3372,  1012,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])}
{'caption': 'A MAN IS SNOW BOARDING IN THE SNOW JUMPING HIGH', 'file_name': 'archive/train2014/train2014/COCO_train2014_000000016344.jpg', 'input_ids': tensor([1037, 2158, 2003, 4586, 9405, 1999, 1996, 4586, 8660, 2152,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,

In [11]:
import torch
torch.manual_seed(0)
ten = torch.randint(low=1, high=10, size=(2, 5, 5))

In [12]:
ten

tensor([[[9, 1, 3, 7, 8],
         [7, 8, 2, 2, 1],
         [9, 3, 7, 4, 2],
         [3, 1, 1, 6, 4],
         [9, 3, 9, 3, 9]],

        [[6, 8, 9, 7, 1],
         [2, 1, 9, 7, 2],
         [7, 2, 9, 9, 8],
         [3, 4, 8, 8, 2],
         [6, 5, 8, 6, 8]]])

In [22]:
mask = torch.ones(1, 16+32, 16+32)
print(mask)

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])


In [40]:
final= torch.tril(mask, diagonal=0, )

In [41]:
final

tensor([[[1., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 0.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [1., 1., 1.,  ..., 1., 0., 0.],
         [1., 1., 1.,  ..., 1., 1., 0.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [39]:
final= torch.tril(mask, diagonal=0, )
final[:, :16, :16] = torch.ones(1, 16, 16)
print(final[0][16])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [ ]:
final.masked_fill(mask, )

tensor([[[1., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 0.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [1., 1., 1.,  ..., 1., 0., 0.],
         [1., 1., 1.,  ..., 1., 1., 0.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])